name: ${{ github.actor }} workflow
run-name: ${{ github.actor }} triggered the workflow

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]
  workflow_dispatch:

jobs:
  github-task-job:
    runs-on: ubuntu-latest

    env:
      GITHUB_ACTIONS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show GITHUB_ACTIONS variable
        run: echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"

      - name: Show branch and repository
        run: |
          echo "Branch: $GITHUB_REF_NAME"
          echo "Repository: $GITHUB_REPOSITORY"

      - name: Show triggering event
        run:  |
          echo "Event: $GITHUB_EVENT_NAME"
